require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MediaInterestsController do

  # This should return the minimal set of attributes required to create a valid
  # MediaInterest. As you add validations to MediaInterest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_profile_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MediaInterestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all media_interests as @media_interests" do
      media_interest = MediaInterest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:media_interests).should eq([media_interest])
    end
  end

  describe "GET show" do
    it "assigns the requested media_interest as @media_interest" do
      media_interest = MediaInterest.create! valid_attributes
      get :show, {:id => media_interest.to_param}, valid_session
      assigns(:media_interest).should eq(media_interest)
    end
  end

  describe "GET new" do
    it "assigns a new media_interest as @media_interest" do
      get :new, {}, valid_session
      assigns(:media_interest).should be_a_new(MediaInterest)
    end
  end

  describe "GET edit" do
    it "assigns the requested media_interest as @media_interest" do
      media_interest = MediaInterest.create! valid_attributes
      get :edit, {:id => media_interest.to_param}, valid_session
      assigns(:media_interest).should eq(media_interest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MediaInterest" do
        expect {
          post :create, {:media_interest => valid_attributes}, valid_session
        }.to change(MediaInterest, :count).by(1)
      end

      it "assigns a newly created media_interest as @media_interest" do
        post :create, {:media_interest => valid_attributes}, valid_session
        assigns(:media_interest).should be_a(MediaInterest)
        assigns(:media_interest).should be_persisted
      end

      it "redirects to the created media_interest" do
        post :create, {:media_interest => valid_attributes}, valid_session
        response.should redirect_to(MediaInterest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved media_interest as @media_interest" do
        # Trigger the behavior that occurs when invalid params are submitted
        MediaInterest.any_instance.stub(:save).and_return(false)
        post :create, {:media_interest => { "user_profile_id" => "invalid value" }}, valid_session
        assigns(:media_interest).should be_a_new(MediaInterest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MediaInterest.any_instance.stub(:save).and_return(false)
        post :create, {:media_interest => { "user_profile_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested media_interest" do
        media_interest = MediaInterest.create! valid_attributes
        # Assuming there are no other media_interests in the database, this
        # specifies that the MediaInterest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MediaInterest.any_instance.should_receive(:update_attributes).with({ "user_profile_id" => "1" })
        put :update, {:id => media_interest.to_param, :media_interest => { "user_profile_id" => "1" }}, valid_session
      end

      it "assigns the requested media_interest as @media_interest" do
        media_interest = MediaInterest.create! valid_attributes
        put :update, {:id => media_interest.to_param, :media_interest => valid_attributes}, valid_session
        assigns(:media_interest).should eq(media_interest)
      end

      it "redirects to the media_interest" do
        media_interest = MediaInterest.create! valid_attributes
        put :update, {:id => media_interest.to_param, :media_interest => valid_attributes}, valid_session
        response.should redirect_to(media_interest)
      end
    end

    describe "with invalid params" do
      it "assigns the media_interest as @media_interest" do
        media_interest = MediaInterest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MediaInterest.any_instance.stub(:save).and_return(false)
        put :update, {:id => media_interest.to_param, :media_interest => { "user_profile_id" => "invalid value" }}, valid_session
        assigns(:media_interest).should eq(media_interest)
      end

      it "re-renders the 'edit' template" do
        media_interest = MediaInterest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MediaInterest.any_instance.stub(:save).and_return(false)
        put :update, {:id => media_interest.to_param, :media_interest => { "user_profile_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested media_interest" do
      media_interest = MediaInterest.create! valid_attributes
      expect {
        delete :destroy, {:id => media_interest.to_param}, valid_session
      }.to change(MediaInterest, :count).by(-1)
    end

    it "redirects to the media_interests list" do
      media_interest = MediaInterest.create! valid_attributes
      delete :destroy, {:id => media_interest.to_param}, valid_session
      response.should redirect_to(media_interests_url)
    end
  end

end
